name: WarpBuf

env:
  WARPBUF_VERSION: 0.0.1

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request: {}
  push:
    paths:
      - 'WarpBuf/**'

jobs:

  build-all-platforms:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-x86_64
            os: ubuntu-latest
            rule: linux
          - name: macos-x86_64
            os: macos-latest
            rule: mac
          - name: win64
            os: windows-latest
            rule: win32
          - name: web
            os: ubuntu-latest
            rule: web

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set permissions
      run: |
        chmod +x WarpBuf/build_unix.sh
        chmod +x WarpBuf/build_windows.bat

    - name: Setup emsdk
      if: matrix.rule == 'web'
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.61
        actions-cache-folder: 'emsdk-cache'

    - name: Install dependencies Ubuntu
      if: matrix.rule == 'linux'
      run: |
        sudo apt install autoconf autogen automake build-essential libasound2-dev \
        libflac-dev libogg-dev libtool libvorbis-dev libopus-dev libmp3lame-dev \
        libmpg123-dev pkg-config python3

    - name: Install dependencies macOS
      if: matrix.rule == 'mac'
      run: |
        brew install autoconf autogen automake flac libogg libtool libvorbis opus mpg123 pkg-config

    - name: make
      run: |
        cd WarpBuf
        make ${{ matrix.rule }}

    # - uses: actions/upload-artifact@v4
    #   if: matrix.rule != 'web'
    #   with:
    #     name: warpbuf-${{ matrix.name }}.zip
    #     path: "WarpBuf/package/warpbuf-${{ env.WARPBUF_VERSION }}"
    #     if-no-files-found: error

    # - uses: actions/upload-artifact@v4
    #   if: matrix.rule == 'web'
    #   with:
    #     name: warpbuf-${{ matrix.name }}.zip
    #     path: "WarpBuf/WarpBuf.chug.wasm"
    #     if-no-files-found: error
